//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioPlayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblListenedSong
    {
        public int ListenedSongID { get; set; }
        public string SongName { get; set; }
        public string ReleaseTime { get; set; }
        public string CompletionTime { get; set; }
        public string ListensUser { get; set; }
    }
}
