//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioPlayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSong
    {
        public int SongID { get; set; }
        public string SongName { get; set; }
        public string SongAuthor { get; set; }
        public string SongDuration { get; set; }
        public int PlaylistUser { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
